#- hosts: nodes
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Installer des packages qui permettent à apt d'être utilisé sur HTTPS
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Ajouter une clé de signature apt pour Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Ajouter un repo apt docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: Supprimer config de containerd
    file:
      path: /etc/containerd/config.toml
      state: absent
  - name: Installer containerd
    apt:
      name: containerd.io
      state: present
  - name: Générer la config de containerd
    shell: |
      containerd config default | sudo tee /etc/containerd/config.toml
      sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
      sed -i 's/systemd_cgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    notify: Restarter Containerd
  - name: Install crictl et activer ip_forwarding
    shell: |
      wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz
      tar zxvf crictl-v1.26.0-linux-amd64.tar.gz -C /usr/bin/crictl /usr/local/bin/
      modprobe br_netfilter
      sysctl -w net.ipv4.ip_forward=1
  - name: Supprimer le swap de /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
    - swap
    - none
  - name: Désactiver swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
  - name: Ajouter une clé de signature apt pour Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: Ajout d'un répo apt pour Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
  - name: Installer les binaires Kubernetes
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl

  handlers :
  - name: Restarter Containerd
    service:
      name: containerd
      state: restarted
